<h1 align="center">NumPy</h1>

In [20]:
import numpy as np

## 1. Creating arrays from Existing Data

Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20.

In [21]:
# Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20.
array_1d = np.array([x for x in range(2, 21, 2)])
print(array_1d)

[ 2  4  6  8 10 12 14 16 18 20]


Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.

In [22]:
#Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.
array_2d = np.array([[x for x in range(2, 12, 2)], [x for x in range(1, 10, 2)]])
print(array_2d)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


## 2. Filling arrays with Specific Values

Create a numpy array of size 10, filled with zeros.

In [23]:
# Create a numpy array of size 10, filled with zeros.
array_0 = np.zeros(10)
print(array_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a numpy matrix of 2*2 integers, filled with ones.

In [24]:
# Create a numpy matrix of 2*2 integers, filled with ones.
matrix_2x2_1 = np.ones((2, 2), dtype=int)
print(matrix_2x2_1)

[[1 1]
 [1 1]]


Create a numpy matrix of 4*4 integers, filled with fives.

In [25]:
# Create a numpy matrix of 4*4 integers, filled with fives.
matrix_4x4_5 = np.full((4, 4), 5, dtype=int)
print(matrix_4x4_5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


## 3. Creating arrays from Ranges

Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 array.

In [26]:
# Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 array.

array = np.arange(2, 41, 2).reshape(4, 5)
print(array)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


Create a numpy array with numbers from 1 to 10, in descending order.

In [27]:
# Create a numpy array with numbers from 1 to 10, in descending order.
array_desc = np.arange(10, 0, -1)
print(array_desc)


[10  9  8  7  6  5  4  3  2  1]


## 4. List vs. array Performance: Introducing %timeit

Use %timeit to compare the execution time of the following two statements. The first uses a list comprehension to create a list of the integers from 0 to 9,999,999, then totals them with the built-in sum function. The second statement does the same thing using an array and its sum method.

       sum([x for x in range(10_000_000)])
       
       np.arange(10_000_000).sum()

In [28]:

%timeit sum([x for x in range(10_000_000)])



539 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%timeit np.arange(10_000_000).sum()

28.3 ms ± 432 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 5. array Operators

Create an array of the values from 1 through 5, then use broadcasting to square each value.

In [30]:
# Create an array of the values from 1 through 5, then use broadcasting to square each value.
array_1_to_5 = np.arange(1, 6)
squared_array = array_1_to_5 ** 2
print(squared_array)

[ 1  4  9 16 25]


## 6. NumPy Calculation Methods

Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row.

In [31]:
# Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row.
grades = np.random.randint(60, 101, size=12).reshape(3, 4)
print("Grades:\n", grades)
average_all = grades.mean()
average_columns = grades.mean(axis=0)
average_rows = grades.mean(axis=1)
print("Average of all grades:", average_all)
print("Average of each column:", average_columns)
print("Average of each row:", average_rows)

Grades:
 [[ 91  60  83  82]
 [ 68  77  77  72]
 [ 64  67  79 100]]
Average of all grades: 76.66666666666667
Average of each column: [74.33333333 68.         79.66666667 84.66666667]
Average of each row: [79.  73.5 77.5]


## 7. Universal Functions

Create an array of the values from 1 through 5, then use the power universal function and broadcasting to cube each value.

In [32]:
# Create an array of the values from 1 through 5, then use the power universal function and broadcasting to cube each value.
array_1_to_5 = np.arange(1, 6)
cubed_array = np.power(array_1_to_5, 3)
print(cubed_array)


[  1   8  27  64 125]


## 8. Indexing and Slicing

Given the following array:
array([[ 1, 2, 3, 4, 5], [6, 7, 8, 9,10],
              [11, 12, 13, 14, 15]])
              
* Select the second row.
* Select the first and third rows.
* Select the middle three columns.

In [35]:
# Given the following array:
# array([[ 1, 2, 3, 4, 5], [6, 7, 8, 9,10],
#               [11, 12, 13, 14, 15]])
              
# * Select the second row.
# * Select the first and third rows.
# * Select the middle three columns.

array = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])
second_row = array[1]
print("Second row:", second_row)   
first_and_third_rows = array[[0, 2]]
print("First and third rows:\n", first_and_third_rows) 
middle_three_columns = array[:, 1:4]
print("Middle three columns:\n", middle_three_columns)



Second row: [ 6  7  8  9 10]
First and third rows:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]]
Middle three columns:
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


## 9. Reshaping and Transposing

Given a 2-by-3 array: 

    array(  [[1, 2, 3],
            [4, 5, 6]])

use hstack and vstack to produce the following array:

    array([[1, 2, 3, 1, 2, 3],
           [4, 5, 6, 4, 5, 6],    
    
       [1, 2, 3, 1, 2, 3 ,    
       [4, 5, 6, 4, 5, 6]])

In [ ]:

array_2x3 = np.array([[1, 2, 3],
                        [4, 5, 6]])
hstacked = np.hstack((array_2x3, array_2x3))
print("Horizontally stacked array:\n", hstacked)
vstacked = np.vstack((hstacked, hstacked))
print("Vertically stacked array:\n", vstacked)


Horizontally stacked array:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
Vertically stacked array:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]
