In [80]:
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib
import matplotlib.pyplot as pp
import seaborn as sns
from IPython import display
from ipywidgets import interact, widgets

In [81]:
# Tạo một ma trận 2x2 có các phần tử là 1.
matrix = np.ones((2, 2))
print(matrix)

# Tạo một mảng rồi sao chép (deep copy) sang một mảng khác.

og_array = np.array([2,3,1,1,0,1,6,3])
copy_array = og_array.copy()
print(og_array)
print(copy_array)

# Tạo một ma trận 3x3x3 với các phần tử ngẫu nhiên kiểu số thực.
random_matrix = np.random.rand(3, 3, 3)
print(random_matrix)

# Tạo một mảng có giá trị từ 10 đến 49.
array_10_49 = np.arange(10, 50)
print(array_10_49)

# Tạo một mảng, hiển thị phần tử đầu tiên của nó.
arr = np.array([2,3,1,1,0,1,6,3])
arr1 = arr[0]
print(arr1)

# Tạo một mảng, hiển thị các phần tử ở những vị trí lẻ.
arr = np.array([2,3,1,1,0,1,6,3])
arr_odd = arr[1::2]
print(arr_odd)

# Tạo một ma trận cấp 2, hiển thị hàng cuối cùng của nó.

matrix_2x2 = np.array([[1,2],[3,4]])
last_row = matrix_2x2[-1]
print(last_row)

# Tạo một mảng, hiển thị tất cả phần tử bằng 2 hay bằng 10.
arr = np.array([2,3,1,1,0,1,6,3,10,12, 2,10])
output = []
for i in arr:
    if i == 2 or i == 10:
        
        output.append(i)
        
print(f"2, tai vi tri: {np.where(arr == 2)[0]}, trong arr")
print(f"10, tai vi tri: {np.where(arr == 10)[0]}, trong arr")
print(output)

# Tạo một mảng, gán phần tử thứ 5 có giá trị là 1.
arr = np.array([2,3,1,1,0,1,6,3])
arr[4] = 1 
print(arr)

# Tạo một ma trận cấp 2, đổi hàng cuối cùng thành các giá trị 1.

matrix_2x2 = np.array([[1,2],[3,4]])
matrix_2x2[-1] = 1
print(matrix_2x2)

[[1. 1.]
 [1. 1.]]
[2 3 1 1 0 1 6 3]
[2 3 1 1 0 1 6 3]
[[[0.03282383 0.37849423 0.46244042]
  [0.34817887 0.07254112 0.30205053]
  [0.47811259 0.26607433 0.56179686]]

 [[0.41008399 0.48361001 0.33653033]
  [0.97053247 0.76606195 0.19020268]
  [0.77750847 0.86388021 0.79047723]]

 [[0.74314442 0.50350761 0.46447078]
  [0.43377357 0.02729774 0.61237118]
  [0.91606002 0.06751817 0.58192073]]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2
[3 1 1 3]
[3 4]
2, tai vi tri: [ 0 10], trong arr
10, tai vi tri: [ 8 11], trong arr
[np.int64(2), np.int64(10), np.int64(2), np.int64(10)]
[2 3 1 1 1 1 6 3]
[[1 2]
 [1 1]]


Lọc các thông tin từ dữ liệu covid-europe các trường sau: iso_code, location, date, new_cases, new_vaccinations, population.

Tách các thông tin bị trùng lắp thành các dataframe con: country(iso_code, location, popluation), cases(iso_code, date, new_cases), vaccinations(iso_code, date, new_vaccinations). Loại bỏ những dòng thừa hoặc không có dữ liệu (không có nghĩa).

Tính tỉ lệ tổng số cases/population, cases/vaccinations của từng quốc gia. Sắp xếp theo chiều giảm dần theo tỉ lệ cases/population.

Lưu ý: Không cung cấp mật khẩu truy cập bài Test và đường dẫn lấy dữ liệu.

In [86]:
data = pd.read_csv('covid-europe.csv')
data 

# Lọc các thông tin từ dữ liệu covid-europe các trường sau: iso_code, location, date, new_cases, new_vaccinations, population.
filter_data = data[['iso_code', 'location', 'date', 'new_cases', 'new_vaccinations', 'population']]
print(filter_data)

# Tách các thông tin bị trùng lắp thành các dataframe con: country(iso_code, location, popluation), cases(iso_code, date, new_cases), vaccinations(iso_code, date, new_vaccinations). Loại bỏ những dòng thừa hoặc không có dữ liệu (không có nghĩa).
country = filter_data[['iso_code', 'location', 'population']].drop_duplicates().dropna()
cases = filter_data[['iso_code', 'date', 'new_cases']].drop_duplicates().dropna()
vaccinations = filter_data[['iso_code', 'date', 'new_vaccinations']].drop_duplicates().dropna()

print(country)
print(cases)
print(vaccinations)


# Tính tỉ lệ tổng số cases/population, cases/vaccinations của từng quốc gia. Sắp xếp theo chiều giảm dần theo tỉ lệ cases/population.
for country_code in country['iso_code']:
    sum_cases = cases[cases['iso_code'] == country_code]['new_cases'].sum()
    population = country[country['iso_code'] == country_code]['population'].values[0]
    sum_vac = vaccinations[vaccinations['iso_code'] == country_code]['new_vaccinations'].sum()
    if population == 0: # zero check (n/0 = inf)
        cases_population = 0
    else:
        cases_population = sum_cases / population
        
    if sum_vac == 0: # zero check (n/0 = inf)
        cases_vaccinations = 0
    else:
        cases_vaccinations = sum_cases / sum_vac
    
    country.loc[country['iso_code'] == country_code, 'cases/population'] = cases_population
    country.loc[country['iso_code'] == country_code, 'cases/vaccinations'] = cases_vaccinations
    
sorted_country_c_p = country.sort_values(by='cases/population', ascending=False)
sorted_country_c_p = sorted_country_c_p[['iso_code', 'location', 'population', 'cases/population']]
print(sorted_country_c_p)

sorted_country_c_v = country.sort_values(by='cases/vaccinations', ascending=False)
sorted_country_c_v = sorted_country_c_v[['iso_code', 'location', 'population', 'cases/vaccinations']]
print(sorted_country_c_v)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16184\1289788027.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('covid-europe.csv')


       iso_code location       date  new_cases  new_vaccinations  population
0           ALB  Albania   1/5/2020        0.0               NaN     2842318
1           ALB  Albania   1/6/2020        0.0               NaN     2842318
2           ALB  Albania   1/7/2020        0.0               NaN     2842318
3           ALB  Albania   1/8/2020        0.0               NaN     2842318
4           ALB  Albania   1/9/2020        0.0               NaN     2842318
...         ...      ...        ...        ...               ...         ...
91026  OWID_WLS    Wales   7/8/2023        NaN               NaN     3170000
91027  OWID_WLS    Wales   7/9/2023        NaN               NaN     3170000
91028  OWID_WLS    Wales  7/10/2023        NaN               NaN     3170000
91029  OWID_WLS    Wales  7/11/2023        NaN               NaN     3170000
91030  OWID_WLS    Wales  7/12/2023        NaN               NaN     3170000

[91031 rows x 6 columns]
       iso_code                location  populatio

In [83]:
# Tính tỉ lệ tổng số cases/population, cases/vaccinations của từng quốc gia. Sắp xếp theo chiều giảm dần theo tỉ lệ cases/population.


cases_population = 0
cases_vaccinations = 0

for country_code in country['iso_code']:
    sum_cases = cases[cases['iso_code'] == country_code]['new_cases'].sum()
    population = country[country['iso_code'] == country_code]['population'].values[0]
    sum_vac = vaccinations[vaccinations['iso_code'] == country_code]['new_vaccinations'].sum()
    if population == 0: # zero check (n/0 = inf)
        cases_population = 0
    else:
        cases_population = sum_cases / population
        
    if sum_vac == 0: # zero check (n/0 = inf)
        cases_vaccinations = 0
    else:
        cases_vaccinations = sum_cases / sum_vac
        
    country.loc[country['iso_code'] == country_code, 'cases/population'] = cases_population
    country.loc[country['iso_code'] == country_code, 'cases/vaccinations'] = cases_vaccinations
    
sorted_country_c_p = country.sort_values(by='cases/population', ascending=False)
sorted_country_c_p = sorted_country_c_p[['iso_code', 'location', 'population', 'cases/population']]
print(sorted_country_c_p)
# sorted_country_c_v = country.sort_values(by='cases/vaccinations', ascending=False)
# sorted_country_c_v = sorted_country_c_v[['iso_code', 'location', 'population', 'cases/vaccinations']]
# print(sorted_country_c_v)


       iso_code                location  population  cases/population
13392       CYP                  Cyprus      896007          0.777237
71788       SMR              San Marino       33690          0.750727
3348        AUT                 Austria     8939617          0.680392
21463       FRO           Faroe Islands       53117          0.652484
78115       SVN                Slovenia     2119843          0.639945
28553       GIB               Gibraltar       32677          0.628883
50328       LUX              Luxembourg      647601          0.607692
1674        AND                 Andorra       79843          0.601368
41948       JEY                  Jersey      110796          0.599218
16748       DNK                 Denmark     5882259          0.584075
25205       FRA                  France    67813000          0.575074
35249       ISL                 Iceland      372903          0.564152
31901       GGY                Guernsey       63329          0.557817
66766       PRT     