In [1]:
import numpy as np
import scipy.stats
import pandas as pd
import matplotlib
import matplotlib.pyplot as pp
import seaborn as sns
from IPython import display
from ipywidgets import interact, widgets

In [34]:
# Tạo một ma trận 2x2 có các phần tử là 1.
matrix = np.ones((2, 2))
print(matrix)

# Tạo một mảng rồi sao chép (deep copy) sang một mảng khác.

og_array = np.array([2,3,1,1,0,1,6,3])
copy_array = og_array.copy()
print(og_array)
print(copy_array)

# Tạo một ma trận 3x3x3 với các phần tử ngẫu nhiên kiểu số thực.
random_matrix = np.random.rand(3, 3, 3)
print(random_matrix)

# Tạo một mảng có giá trị từ 10 đến 49.
array_10_49 = np.arange(10, 50)
print(array_10_49)

# Tạo một mảng, hiển thị phần tử đầu tiên của nó.
arr = np.array([2,3,1,1,0,1,6,3])
arr1 = arr[0]
print(arr1)

# Tạo một mảng, hiển thị các phần tử ở những vị trí lẻ.
arr = np.array([2,3,1,1,0,1,6,3])
arr_odd = arr[1::2]
print(arr_odd)

# Tạo một ma trận cấp 2, hiển thị hàng cuối cùng của nó.

matrix_2d = np.array([[1,2],[3,4]])
last_row = matrix_2d[-1]
print(last_row)

# Tạo một mảng, hiển thị tất cả phần tử bằng 2 hay bằng 10.
arr = np.array([2,3,1,1,0,1,6,3,10,12, 2,10])
output = []
for i in arr:
    if i == 2 or i == 10:
        output.append(i)

print(output)

# Tạo một mảng, gán phần tử thứ 5 có giá trị là 1.
arr = np.array([2,3,1,1,0,1,6,3])
arr[4] = 1 
print(arr)

# Tạo một ma trận cấp 2, đổi hàng cuối cùng thành các giá trị 1.

matrix_2x2 = np.array([[1,2],[3,4]])
matrix_2x2[-1] = 1
print(matrix_2x2)

[[1. 1.]
 [1. 1.]]
[2 3 1 1 0 1 6 3]
[2 3 1 1 0 1 6 3]
[[[0.92149875 0.68137168 0.34816379]
  [0.05672999 0.43530654 0.13723995]
  [0.73542156 0.140294   0.0702423 ]]

 [[0.29966965 0.31801061 0.06701726]
  [0.56485672 0.41426564 0.68800753]
  [0.22210785 0.98503088 0.65979494]]

 [[0.59601972 0.99819958 0.21068162]
  [0.01028364 0.87143086 0.022238  ]
  [0.37366425 0.06366103 0.15278357]]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2
[3 1 1 3]
[3 4]
[np.int64(2), np.int64(10), np.int64(2), np.int64(10)]
[2 3 1 1 1 1 6 3]
[[1 2]
 [1 1]]


Lọc các thông tin từ dữ liệu covid-europe các trường sau: iso_code, location, date, new_cases, new_vaccinations, population.

Tách các thông tin bị trùng lắp thành các dataframe con: country(iso_code, location, popluation), cases(iso_code, date, new_cases), vaccinations(iso_code, date, new_vaccinations). Loại bỏ những dòng thừa hoặc không có dữ liệu (không có nghĩa).

Tính tỉ lệ tổng số cases/population, cases/vaccinations của từng quốc gia. Sắp xếp theo chiều giảm dần theo tỉ lệ cases/population.

Lưu ý: Không cung cấp mật khẩu truy cập bài Test và đường dẫn lấy dữ liệu.

In [ ]:
data = pd.read_csv('covid-europe.csv')