In [7]:
import numpy as np
import pandas as pd

## 10 Câu đầu

### 1.Khởi tạo Mảng 

- `ones`: tạo mảng toàn số 1. (`np.ones((2,3))` tạo ma trận 2x3 toàn số 1)
- `random`: tạo mảng ngẫu nhiên. (`np.random.rand(2,3)` tạo ma trận 2x3 với các số ngẫu nhiên từ 0 đến 1)
- `linspace`: tạo mảng với các giá trị chia đều nhau trong một khoảng xác định. (`np.linspace(0, 1, 5)` tạo mảng gồm 5 giá trị từ 0 đến 1)
- `arange`: tạo mảng với các giá trị trong một khoảng xác định với bước nhảy cụ thể. (`np.arange(0, 10, 2)` tạo mảng gồm các số từ 0 đến 10 với bước nhảy là 2)
- `zeros`: tạo mảng toàn số 0. (`np.zeros((3,4))` tạo ma trận 3x4 toàn số 0)
- `eye`: tạo ma trận đơn vị (identity matrix). (`np.eye(3)` tạo ma trận 3x3 với đường chéo chính là 1, các phần tử khác là 0)
- `full`: tạo mảng với tất cả các phần tử có cùng một giá trị xác định. (`np.full((2,3), 7)` tạo ma trận 2x3 với tất cả các phần tử là số 7)

* **Tạo một ma trận 3x3 toàn số 0.**
```python
matrix_zeros = np.zeros((3, 3))
print(matrix_zeros)

```


* **Tạo một ma trận đơn vị (Identity Matrix) cấp 3 (đường chéo là 1, còn lại là 0).**
```python
identity_matrix = np.eye(3)
print(identity_matrix)

```


* **Tạo một ma trận 2x5 với tất cả các phần tử đều là số 7.**
```python
matrix_full = np.full((2, 5), 7)
print(matrix_full)

```


* **Tạo một mảng gồm 5 giá trị chia đều nhau trong khoảng từ 0 đến 1 (linspace).**
```python
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

```



### 2. Truy xuất & Cắt lát 

* **Tạo một mảng, hiển thị hàng cuối.**
```python
arr = np.array([10, 20, 30, 40, 50])
last_element = arr[-1]
print(last_element)
```
* **Tạo một mảng, hiển thị các phần tử ở vị trí lẻ (1, 3, 5,...).**
```python
arr = np.array([10, 20, 30, 40, 50, 60, 70])
odd_indexed_elements = arr[1::2] # Bắt đầu từ chỉ số 1, bước nhảy 2
print(odd_indexed_elements)
```
* **Tạo một mảng, hiển thị mảng đó theo thứ tự đảo ngược.**
```python
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

```

* **Tạo một ma trận 3x3, hiển thị cột thứ 2 (chỉ số 1) của nó.**
```python
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
col_2 = mat[:, 1] # Dấu : nghĩa là lấy mọi hàng, 1 là cột chỉ số 1
print(col_2)

```


* **Tạo một ma trận 3x3, hiển thị ma trận con 2x2 ở góc trên bên trái.**
```python
sub_mat = mat[:2, :2] # Lấy hàng 0 đến 1, cột 0 đến 1
print(sub_mat)

```



### 3. Lọc dữ liệu

* **Tạo một mảng, tìm và hiển thị tất cả các số lớn hơn 5.**
```python
arr = np.array([2, 8, 1, 6, 0, 10])
print(arr[arr > 5]) 

```


* **Tạo một mảng, hiển thị các chỉ số (vị trí) của các phần tử bằng 0.**
```python
arr = np.array([1, 0, 2, 0, 3])
indices = np.where(arr == 0)
print(indices)

```



### 4. Thay đổi hình dạng 

* **Tạo một mảng 1 chiều gồm 10 phần tử (0-9), sau đó đổi nó thành ma trận 2x5.**
```python
arr = np.arange(10)
matrix_2x5 = arr.reshape(2, 5)
print(matrix_2x5)

```

* **Tạo một ma trận 2x3, sau đó chuyển vị (transpose) thành ma trận 3x2.**
```python
mat = np.array([[1, 2, 3], 
                [4, 5, 6]])
mat_T = mat.T
print(mat_T)

```
### 5. Extra

Các bài tập yêu cầu tính toán trên toàn bộ mảng.

* **Tạo một mảng ngẫu nhiên, tìm giá trị lớn nhất, nhỏ nhất và trung bình.**
```python
arr = np.random.rand(5)
print(f"Max: {arr.max()}")
print(f"Min: {arr.min()}")
print(f"Mean: {arr.mean()}")

```

## CSV

### Phần 1: Các dạng câu hỏi mở rộng tương tự

Ngoài việc tính tổng và tỷ lệ, đề bài có thể yêu cầu bạn làm việc với **Thời gian** hoặc **Điều kiện lọc** phức tạp hơn.

#### Dạng 1: Thống kê theo thời gian (Time-series Analysis)

*Câu hỏi:* Thay vì tính tổng toàn bộ, hãy tính **tổng số ca mắc mới theo từng tháng** của từng quốc gia.

```python
# Chuyển đổi sang datetime
data['date'] = pd.to_datetime(data['date'])
# Tạo cột tháng
data['month'] = data['date'].dt.to_period('M')
# Gom nhóm theo quốc gia và tháng
monthly_stats = data.groupby(['iso_code', 'month'])['new_cases'].sum().reset_index()

```



#### Dạng 2: Tìm giá trị lớn nhất/nhỏ nhất

*Câu hỏi:* Tìm **ngày có số ca mắc mới cao nhất** (đỉnh dịch) cho mỗi quốc gia.

* **Mấu chốt:** Sử dụng `idxmax()` hay là `idxmin()` hoặc sắp xếp rồi lấy dòng đầu tiên của mỗi nhóm.
* **Code mẫu:**
```python
# Tìm index của dòng có new_cases lớn nhất theo từng quốc gia
idx = data.groupby('iso_code')['new_cases'].idxmax()
# Lọc ra các dòng đó
peak_days = data.loc[idx, ['location', 'date', 'new_cases']]

```

#### Dạng 3: Join/Merge bảng (Nếu dữ liệu nằm ở nhiều file)

*Câu hỏi:* Giả sử bạn có bảng `cases` riêng và bảng `vaccinations` riêng. Hãy gộp chúng lại dựa trên `iso_code` và `date` để tính toán.

* **Code mẫu:**
```python
merged_df = pd.merge(cases, vaccinations, on=['iso_code', 'date'], how='inner')

```



---

### Phần 2: Khung giàn bài (Framework) để giải mọi bài toán Pandas

Để làm bài nhanh và chuẩn (tránh dùng vòng lặp `for` như trong bài mẫu của bạn vì nó xử lý chậm với dữ liệu lớn), hãy tuân thủ quy trình 5 bước sau:

#### Bước 1: Load & Filter (Đọc và Lọc cột cần thiết)

Luôn bắt đầu bằng việc chỉ giữ lại những gì cần dùng để giảm tải bộ nhớ.

```python
df = pd.read_csv('file.csv')
cols_to_use = ['iso_code', 'location', 'date', 'new_cases', 'population']
df = df[cols_to_use]

```

#### Bước 2: Data Cleaning (Làm sạch)

Xử lý dữ liệu rác, trùng lặp hoặc thiếu.

```python
# Xóa trùng lặp
df = df.drop_duplicates()

# Xử lý NaN (Thay thế bằng 0 hoặc xóa dòng)
df = df.fillna(0) 
# Hoặc: df = df.dropna(subset=['iso_code'])

```

#### Bước 3: Group & Aggregate (Gom nhóm và Tính toán) **(Quan trọng nhất)**

Thay vì dùng vòng lặp `for` để chạy qua từng quốc gia (rất chậm), hãy dùng `groupby`. Đây là kỹ thuật "chia để trị" của Pandas.

* Muốn tính tổng? Dùng `.sum()`
* Muốn tính trung bình? Dùng `.mean()`
* Muốn đếm? Dùng `.count()`

```python
# Gom theo quốc gia, tính tổng ca mắc và tổng vắc xin cùng lúc
# Quy tắc: df.groupby('Cột muốn gom')['Cột muốn tính'].phép_tính()
stats = df.groupby(['iso_code', 'location', 'population'])[['new_cases', 'new_vaccinations']].sum().reset_index()

```

#### Bước 4: Feature Engineering (Tạo cột mới từ dữ liệu đã gom)

Thực hiện các phép chia, nhân, cộng trừ trên các cột. Pandas cho phép tính toán trên toàn bộ cột (vectorization) mà không cần loop.

```python
# Tính tỷ lệ (Tự động xử lý cho mọi dòng cùng lúc)
# Lưu ý: Nên xử lý chia cho 0 nếu cần
stats['cases_per_pop'] = stats['new_cases'] / stats['population']

```

#### Bước 5: Sort & Format (Sắp xếp và Trình bày)

```python
# Sắp xếp giảm dần
result = stats.sort_values(by='cases_per_pop', ascending=False)

# Chọn lại cột để hiển thị cuối cùng
final_view = result[['location', 'cases_per_pop']]
print(final_view)

```

### Tối ưu hóa code của bạn (Lời khuyên)

Trong đoạn code bạn gửi, đoạn dùng `for country_code in country['iso_code']:` là cách tư duy lập trình căn bản (C/Java). Trong Python/Pandas Data Science, người ta ưu tiên cách làm sau (gọn hơn và nhanh hơn gấp nhiều lần):

```python
# Cách làm chuẩn Pandas (Thay thế cho toàn bộ vòng lặp for của bạn)

# 1. Gom nhóm tính tổng cases và vaccinations theo iso_code
grouped = filter_data.groupby(['iso_code', 'population'])[['new_cases', 'new_vaccinations']].sum().reset_index()

# 2. Tính toán trực tiếp trên cột (Vectorization)
grouped['cases/population'] = grouped['new_cases'] / grouped['population']

# Xử lý chia cho 0 cho cột vaccinations (nếu sum_vac = 0)
# np.where(điều_kiện, giá_trị_nếu_đúng, giá_trị_nếu_sai)
grouped['cases/vaccinations'] = np.where(grouped['new_vaccinations'] == 0, 
                                         0, 
                                         grouped['new_cases'] / grouped['new_vaccinations'])

# 3. Sắp xếp
sorted_df = grouped.sort_values(by='cases/population', ascending=False)
print(sorted_df)

```

In [8]:
# Tạo một ma trận 2x2 có các phần tử là 1.
matrix = np.ones((2, 2))
print(matrix)

# Tạo một mảng rồi sao chép (deep copy) sang một mảng khác.

og_array = np.array([2,3,1,1,0,1,6,3])
copy_array = og_array.copy()
print(og_array)
print(copy_array)

# Tạo một ma trận 3x3x3 với các phần tử ngẫu nhiên kiểu số thực.
random_matrix = np.random.rand(3, 3, 3)
print(random_matrix)

# Tạo một mảng có giá trị từ 10 đến 49.
array_10_49 = np.arange(10, 50)
print(array_10_49)

# Tạo một mảng, hiển thị phần tử đầu tiên của nó.
arr = np.array([2,3,1,1,0,1,6,3])
arr1 = arr[0]
print(arr1)

# Tạo một mảng, hiển thị các phần tử ở những vị trí lẻ.
arr = np.array([2,3,1,1,0,1,6,3])
arr_odd = arr[1::2]
print(arr_odd)

# Tạo một ma trận cấp 2, hiển thị hàng cuối cùng của nó.

matrix_2x2 = np.array([[1,2],[3,4]])
last_row = matrix_2x2[-1]
print(last_row)

# Tạo một mảng, hiển thị tất cả phần tử bằng 2 hay bằng 10.
arr = np.array([2,3,1,1,0,1,6,3,10,12, 2,10])
output = []
for i in arr:
    if i == 2 or i == 10:
        
        output.append(i)
        
print(f"2, tai vi tri: {np.where(arr == 2)[0]}, trong arr")
print(f"10, tai vi tri: {np.where(arr == 10)[0]}, trong arr")
print(output)

# Tạo một mảng, gán phần tử thứ 5 có giá trị là 1.
arr = np.array([2,3,1,1,0,1,6,3])
arr[4] = 1 
print(arr)

# Tạo một ma trận cấp 2, đổi hàng cuối cùng thành các giá trị 1.

matrix_2x2 = np.array([[1,2],[3,4]])
matrix_2x2[-1] = 1
print(matrix_2x2)

[[1. 1.]
 [1. 1.]]
[2 3 1 1 0 1 6 3]
[2 3 1 1 0 1 6 3]
[[[0.50586018 0.61020383 0.3020125 ]
  [0.1944017  0.53948244 0.48377139]
  [0.07392803 0.70754674 0.62909544]]

 [[0.99731827 0.70443749 0.43466397]
  [0.2969004  0.29890996 0.39903134]
  [0.46080131 0.19513538 0.9448816 ]]

 [[0.53409257 0.93165725 0.33606245]
  [0.54739031 0.44093727 0.30416675]
  [0.84870729 0.45018801 0.21877085]]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2
[3 1 1 3]
[3 4]
2, tai vi tri: [ 0 10], trong arr
10, tai vi tri: [ 8 11], trong arr
[np.int64(2), np.int64(10), np.int64(2), np.int64(10)]
[2 3 1 1 1 1 6 3]
[[1 2]
 [1 1]]


In [9]:
data = pd.read_csv('covid-europe.csv')
data 

# Lọc các thông tin từ dữ liệu covid-europe các trường sau: iso_code, location, date, new_cases, new_vaccinations, population.
filter_data = data[['iso_code', 'location', 'date', 'new_cases', 'new_vaccinations', 'population']]
print(filter_data)

# Tách các thông tin bị trùng lắp thành các dataframe con: country(iso_code, location, popluation), cases(iso_code, date, new_cases), vaccinations(iso_code, date, new_vaccinations). Loại bỏ những dòng thừa hoặc không có dữ liệu (không có nghĩa).
country = filter_data[['iso_code', 'location', 'population']].drop_duplicates().dropna()
cases = filter_data[['iso_code', 'date', 'new_cases']].drop_duplicates().dropna()
vaccinations = filter_data[['iso_code', 'date', 'new_vaccinations']].drop_duplicates().dropna()

print(country)
print(cases)
print(vaccinations)


# Tính tỉ lệ tổng số cases/population, cases/vaccinations của từng quốc gia. Sắp xếp theo chiều giảm dần theo tỉ lệ cases/population.
for country_code in country['iso_code']:
    sum_cases = cases[cases['iso_code'] == country_code]['new_cases'].sum()
    population = country[country['iso_code'] == country_code]['population'].values[0]
    sum_vac = vaccinations[vaccinations['iso_code'] == country_code]['new_vaccinations'].sum()
    if population == 0: # zero check (n/0 = inf)
        cases_population = 0
    else:
        cases_population = sum_cases / population
        
    if sum_vac == 0: # zero check (n/0 = inf)
        cases_vaccinations = 0
    else:
        cases_vaccinations = sum_cases / sum_vac
    
    country.loc[country['iso_code'] == country_code, 'cases/population'] = cases_population
    country.loc[country['iso_code'] == country_code, 'cases/vaccinations'] = cases_vaccinations
    
sorted_country_c_p = country.sort_values(by='cases/population', ascending=False)
sorted_country_c_p = sorted_country_c_p[['iso_code', 'location', 'population', 'cases/population']]
print(sorted_country_c_p)

sorted_country_c_v = country.sort_values(by='cases/vaccinations', ascending=False)
sorted_country_c_v = sorted_country_c_v[['iso_code', 'location', 'population', 'cases/vaccinations']]
print(sorted_country_c_v)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20492\1289788027.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('covid-europe.csv')


       iso_code location       date  new_cases  new_vaccinations  population
0           ALB  Albania   1/5/2020        0.0               NaN     2842318
1           ALB  Albania   1/6/2020        0.0               NaN     2842318
2           ALB  Albania   1/7/2020        0.0               NaN     2842318
3           ALB  Albania   1/8/2020        0.0               NaN     2842318
4           ALB  Albania   1/9/2020        0.0               NaN     2842318
...         ...      ...        ...        ...               ...         ...
91026  OWID_WLS    Wales   7/8/2023        NaN               NaN     3170000
91027  OWID_WLS    Wales   7/9/2023        NaN               NaN     3170000
91028  OWID_WLS    Wales  7/10/2023        NaN               NaN     3170000
91029  OWID_WLS    Wales  7/11/2023        NaN               NaN     3170000
91030  OWID_WLS    Wales  7/12/2023        NaN               NaN     3170000

[91031 rows x 6 columns]
       iso_code                location  populatio